version: '2'
services:
  scubadivelog-app:
    image: scubadivelog
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://scubadivelog-mariadb:3306/scubadivelog
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  scubadivelog-mariadb:
    extends:
      file: mariadb.yml
      service: scubadivelog-mariadb
